# Generated by Django 3.2 on 2021-07-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_customerdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='name',
            new_name='Assignto',
        ),
    ]
